replicaCount: 1
revisionHistoryLimit: 0

## PodDisruptionBudget
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
# maxUnavailable: 1

image:
  repository: docker.pkg.github.com/t3n/apache-fop-server/apache-fop-server
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - regsecret

service:
  type: ClusterIP
  annotations: {}
