{{- if or (eq .Values.type "ExternalName") (and .Values.addresses .Values.ports) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-service.fullname" . }}
  labels:
    {{ include "external-service.labels" . | indent 4 | trim }}
spec:
  type: {{ .Values.type }}
{{- if eq .Values.type "ExternalName" }}
  externalName: {{ required "`.Values.externalName` is not set." .Values.externalName}}
{{- else}}
  ports:
{{- range .Values.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
