{{- if .Values.secretFiles -}}
{{- $root := . }}
{{- range $key, $files := .Values.secretFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "general.fullname" $root }}-{{ $key }}
  labels: {{- include "general.labels" $root | nindent 4 }}
data:
{{- range $key, $value := $files.files }}
  {{ $key }}: |-
    {{ $value }}
{{- end }}
{{- end }}
{{- end -}}
