{{- if (eq (.Values.replicaCount | toString) "0") }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "unms.fullname" . }}
  labels:
    {{ include "unms.labels" . | indent 4 | trim }}
spec:
  selector:
    matchLabels:
      {{ include "unms.selector" . | indent 8 | trim }}
  maxUnavailable: {{ if .Values.maxUnavailable }}{{ .Values.maxUnavailable }}{{- else }}{{ ceil (div .Values.replicaCount 2) }}{{- end }}
{{- end }}
