{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "unms.fullname" . }}
  labels:
    {{ include "unms.labels" . | indent 4 | trim }}
{{- with .Values.persistence.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
