apiVersion: v1
kind: Service
metadata:
  name: {{ include "unms.fullname" . }}
  labels:
    app: {{ include "unms.name" . }}
    chart: {{ include "unms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8081
      protocol: TCP
    - name: socket
      port: 8082
      protocol: TCP
    - name: shell
      port: 8083
      protocol: TCP
    - name: api
      port: 8084
      protocol: TCP
  selector:
    app: {{ include "unms.name" . }}
    release: {{ .Release.Name }}
