apiVersion: v1
kind: Service
metadata:
  name: {{ include "unms.fullname" . }}-nginx
  labels:
    {{ include "unms.labels-nginx" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
    - name: encrypt
      port: 12345
      protocol: TCP
  selector:
    {{ include "unms.selector-nginx" . | indent 4 | trim }}
