apiVersion: v1
kind: Service
metadata:
  name: {{ include "snipeit.fullname" . }}
  labels:
    {{ include "snipeit.labels" . | indent 4 | trim }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    {{ include "snipeit.selector" . | indent 4 | trim }}
