{{- if .Values.authentication.passwordEntries }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
data:
  passwordfile: {{ .Values.authentication.passwordEntries | b64enc | quote }}
{{- end }}
