kind: Secret
apiVersion: v1
metadata:
  name: {{ include "sftp-gcs.fullname" . }}
  labels: {{- include "sftp-gcs.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: |-
    {{ .Values.credentials }}
  id_rsa: |-
    {{ .Values.privateKey }}
