replicaCount: 1

image:
  repository: gcr.io/cloudsql-docker/gce-proxy
  tag: 1.16
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  sessionAffinity: ""
  annotations: {}

## Configure resource requests and limits
## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  create: true

serviceAccount:
  create: true
  name: ""

## Set the GCP service account key JSON file.
## Service account has access be set to Cloud SQL instances
## the key must be encoded with base64
## e.g. `cat service-account.json | base64`
## only used if no existing secret is specified
##
serviceAccountKey: ""

## SQL connection settings
##
cloudsql:
  ## PostgreSQL/MySQL instances:
  ## update with your GCP project, the region of your Cloud SQL instance
  ## and the name of your Cloud SQL instance
  ## PostgreSQL port 5432 or MySQL port 3306, or other port you set for your SQL instance.
  ## Use different ports for different instances.
  instances:
    # GCP instance name.
  - instance: "instance"
    # Optional abbreviation used to override the truncated instance name if the
    # 15 character instance name prefix is not unique for use as a port
    # identifier.
    instanceShortName: ""
    # GCP project where the instance exists.
    project: "project"
    # GCP region where the instance exists.
    region: "region"
    # Port number for the proxy to expose for this instance.
    port: 5432
