apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh.fullname" . }}-authorized
  labels:
    {{ include "ssh.labels" . | indent 4 | trim }}
data:
{{- with .Values.users }}
  {{- range $key, $value := . }}
  {{ $key }}: |-
    {{ $value | b64enc}}
  {{- end }}
{{- end }}
