apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-video.fullname" . }}-udp
  labels:
    {{ include "unifi-video.labels" . | indent 4 | trim }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{ if (.Values.service.loadBalancerIP) and eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{ end }}
  ports:
    - name: talkback
      port: 7004
      protocol: UDP
  selector:
    {{ include "unifi-video.selector" . | indent 4 | trim }}
