{{- if not .Values.existingSecret }}
{{- if or (not .Values.allowEmptyRootPassword) (or .Values.mysqlRootPassword .Values.mysqlPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mysqlRootPassword }}
  mysql-root-password: {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{- else }}
  {{- if not .Values.allowEmptyRootPassword }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.mysqlPassword }}
  mysql-password: {{ .Values.mysqlPassword | b64enc | quote }}
  {{- else }}
  {{- if not .Values.allowEmptyRootPassword }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.ssl.enabled }}
{{- if .Values.ssl.certificates }}
{{- range .Values.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  ca.pem: {{ .ca | b64enc }}
  server-cert.pem: {{ .cert | b64enc }}
  server-key.pem: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
