{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql.serviceAccountName" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
{{- end }}
