{{- if .Values.cronjobs.archive.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}-archive
  labels: {{- include "matomo.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjobs.archive.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjobs.archive.concurrencyPolicy | default "Allow" }}
{{- if .Values.cronjobs.archive.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjobs.archive.startingDeadlineSeconds }}
{{- end }}
  successfulJobsHistoryLimit: {{ .Values.cronjobs.archive.successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .Values.cronjobs.archive.failedJobsHistoryLimit | default 1 }}
  jobTemplate:
    spec:
      template:
        spec:
        {{- if .Values.image.pullSecrets }}
          imagePullSecrets:
          {{- range .Values.image.pullSecrets }}
            - name: {{ . }}
          {{- end }}
        {{- end }}
          restartPolicy: Never
          containers:
          - name: {{ include "matomo.name" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: MATOMO_DATABASE_HOST
                value: {{ include "matomo.databaseHost" . | quote }}
              - name: MATOMO_DATABASE_ADAPTER
                value: {{ .Values.database.adapter | quote }}
              - name: MATOMO_DATABASE_TABLES_PREFIX
                value: {{ .Values.database.tables_prefix | quote }}
              - name: MATOMO_DATABASE_DBNAME
                value: {{ .Values.database.dbname | quote }}
              - name: MATOMO_GENERAL_SALT
                value: {{ required "`.Values.salt` is not set." .Values.salt | quote }}
            {{- range $key, $value := .Values.extraEnvs }}
              - name: {{ $key }}
                value: {{ $value | quote }}
            {{- end }}
            envFrom:
              - secretRef:
                  name: {{ include "matomo.fullname" . }}-envs
            args: ['su', 'www-data', '-s', '/bin/sh', '-c', '/usr/local/bin/php /var/www/html/console core:archive --url={{ include "matomo.fullname" . }} --concurrent-requests-per-website={{ .Values.cronjobs.archive.concurrentRequests }}']
          {{- with .Values.cronjobs.archive.resources }}
            resources:
              {{ toYaml . | indent 14 | trim}}
          {{- end }}
            volumeMounts:
              - name: data
                mountPath: {{ .Values.persistence.mountPath }}
                subPath: {{ .Values.persistence.subPath }}
          volumes:
            - name: data
            {{- if .Values.persistence.enabled }}
              persistentVolumeClaim:
                claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "matomo.fullname" . }}{{- end }}
            {{- else }}
              emptyDir: {}
            {{- end }}
{{- end -}}
