dependencies:
- name: redis
  version: ^0.0.3
  repository: gs://yeebase-private-helm-charts/
- name: helper
  version: 0.1.0
  repository: gs://yeebase-private-helm-charts/
- name: postgresql
  version: ^0.8.3
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: rabbitmq-ha
  version: ^1.6.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: fluentd
  version: ^1.10.0
  repository: https://kubernetes-charts.storage.googleapis.com/
