version: 2
jobs:
  test:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run: |
          wget -q ${HELM_URL}/${HELM_TARBALL}
          tar xzfv ${HELM_TARBALL}
          export PATH=`pwd`/linux-amd64/:$PATH
          echo 'export PATH=`pwd`/linux-amd64/:$PATH' >> $BASH_ENV
          helm init --client-only
          helm repo add yeebase https://storage.googleapis.com/yeebase-helm-charts
      - run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json
          ./helm_lint.sh

  release:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - run: |
          wget -q ${HELM_URL}/${HELM_TARBALL}
          tar xzfv ${HELM_TARBALL}
          export PATH=`pwd`/linux-amd64/:$PATH
          echo 'export PATH=`pwd`/linux-amd64/:$PATH' >> $BASH_ENV
          helm init --client-only
          helm plugin install https://github.com/nouney/helm-gcs
          echo "$SERVICE_ACCOUNT_JSON" > key.json
          gcloud auth activate-service-account --key-file key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json
          helm repo remove local
          helm repo add yeebase https://storage.googleapis.com/yeebase-helm-charts
      - run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json
          ./repo_sync.sh

workflows:
  version: 2
  test-release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
