version: 2

helm_environment: &helm_environment
  HELM_URL: "https://get.helm.sh"
  HELM_TARBALL: "helm-v3.1.2-linux-amd64.tar.gz"

jobs:
  test:
    environment:
      *helm_environment
    docker:
      - image: google/cloud-sdk:alpine
    resource_class: small
    steps:
      - checkout
      - run: |
          wget -q ${HELM_URL}/${HELM_TARBALL}
          tar xzfv ${HELM_TARBALL}
          export PATH=`pwd`/linux-amd64/:$PATH
          echo 'export PATH=`pwd`/linux-amd64/:$PATH' >> $BASH_ENV
          helm repo add stable https://charts.helm.sh/stable
          helm repo add t3n https://storage.googleapis.com/t3n-helm-charts
      - run: |
          ./helm_lint.sh

  release:
    environment:
      *helm_environment
    docker:
      - image: google/cloud-sdk:413.0.0-alpine
    resource_class: small
    steps:
      - checkout
      - run: |
          wget -q ${HELM_URL}/${HELM_TARBALL}
          tar xzfv ${HELM_TARBALL}
          export PATH=`pwd`/linux-amd64/:$PATH
          echo 'export PATH=`pwd`/linux-amd64/:$PATH' >> $BASH_ENV
          helm repo add stable https://charts.helm.sh/stable
          helm repo add t3n https://storage.googleapis.com/t3n-helm-charts
          echo "$SERVICE_ACCOUNT_JSON" > key.json
          gcloud auth activate-service-account --key-file key.json
      - run: |
          ./repo_sync.sh

workflows:
  version: 2
  test-release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
