apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fop.fullname" . }}
  labels:
    app: {{ include "fop.name" . }}
    chart: {{ include "fop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "fop.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "fop.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "fop.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
        {{- with .Values.resources }}
          resources:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
