{{- if .Values.secretFiles -}}
{{- $root := . }}
{{- range $key, $files := .Values.secretFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python.fullname" $root }}-{{ $key }}
  labels:
    app: {{ include "python.name" $root }}
    chart: {{ include "python.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
data:
{{- range $key, $value := $files.files }}
  {{ $key }}: |-
    {{ $value }}
{{- end }}
{{- end }}
{{- end -}}
