apiVersion: v1
kind: Service
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    app: {{ include "python.name" . }}
    chart: {{ include "python.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.name }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ include "python.name" . }}
    release: {{ .Release.Name }}
