apiVersion: v1
kind: Service
metadata:
  name: {{ include "python.fullname" . }}
  labels: {{- include "python.labels" . | nindent 4 }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.name }}
      name: {{ .Values.service.name }}
  selector: {{- include "python.selector" . | nindent 4 }}
