{{- if .Values.ingress.enabled -}}
{{- $fullName := include "snowplow.fullname" . }}
{{- $ingressPath := .Values.ingress.path }}
{{- $serviceName := .Values.service.name }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "snowplow.fullname" . }}
  labels:
    {{ include "snowplow.labels" . | indent 4 | trim }}
{{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
