kind: Secret
apiVersion: v1
metadata:
  name: {{ include "snowplow.fullname" . }}
  labels:
    {{ include "snowplow.labels" . | indent 4 | trim }}
data:
  credentials.json:
    {{ .Values.config.snowplow.serviceAccountKey }}