apiVersion: v2
name: python
version: 2.0.2
deprecated: true

dependencies:
- name: redis-ha
  version: ~3.11.0
  repository: https://charts.helm.sh/stable
  condition: redis.enabled
- name: postgresql
  version: ~8.6.0
  repository: https://charts.helm.sh/stable
  condition: postgresql.enabled
- name: postgresql-backup
  version: ~0.0.1
  repository: https://storage.googleapis.com/t3n-helm-charts
  condition: postgresql-backup.enabled
