apiVersion: v2
name: python
version: 2.0.1

dependencies:
- name: redis-ha
  version: ~3.11.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: postgresql
  version: ~8.6.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
