apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-backup.fullname" . }}
  labels: {{- include "postgresql-backup.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "scripts/*").AsConfig . | indent 2 }}
