kind: Secret
apiVersion: v1
metadata:
  name: {{ template "postgresql-backup.fullname" . }}-gcs
  labels: {{- include "postgresql-backup.labels" . | nindent 4 }}
type: Opaque
data:
  key.json: |-
    {{ .Values.gcs.serviceAccountKey }}
