kind: Secret
apiVersion: v1
metadata:
  name: {{ template "postgresql-backup.fullname" . }}-postgresql
  labels: {{- include "postgresql-backup.labels" . | nindent 4 }}
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASS: {{ .Values.database.pass | b64enc | quote }}
