{{- if and .Values.secretFiles (not .Values.existingSecret) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels: {{- include "cronjob.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretFiles }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
