{{- if .Values.ingress.enabled }}
{{- $fullName := .Chart.Name }}
{{- $ingressPath := .Values.ingress.path }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "dashkiosk.fullname" . }}
  labels:
    {{ include "dashkiosk.labels" . | indent 4 | trim }}
{{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- end }}
