kind: Secret
apiVersion: v1
metadata:
  name: {{ include "dashkiosk.fullname" . }}
  labels:
    {{ include "dashkiosk.labels" . | indent 4 | trim }}
data:
  db__password: {{ .Values.db.pass | b64enc | quote }}
